### ISSUE TITLE
HistoryManager Prefix Search 12 incompatible with GNOME 40

### ISSUE THREAD

**Issue by audreytoskin** [sustmi/gnome-shell-extension-historymanager-prefix-search#2]
I'm testing the upcoming GNOME 40 in a virtual machine of Rawhide (development branch of Fedora) x86_64. I'm using the RPM build of HistoryManager Prefix search v12.

Looking Glass shows no error messages for HistoryManager (because the extension hasn't been enabled yet). But in the GNOME Extensions app, there's a red ⛔ warning icon, and the toggle switch to enable HistoryManager is grayed out. If you click the gears icon to see HistoryManager settings, you get a dialog that says "Something went wrong" and the following error message:

```
Gtk.BuilderError: /usr/share/gnome-shell/extensions/historymanager-prefix-search@sustmidown.centrum.cz/prefs.xml:8:35 Invalid property: GtkBox.margin_left

Stack trace:
  _init@/usr/share/gnome-shell/extensions/historymanager-prefix-search@sustmidown.centrum.cz/prefs.js:34:17
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/usr/share/gnome-shell/extensions/historymanager-prefix-search@sustmidown.centrum.cz/prefs.js:77:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by sustmi** [comment]
Good news!
I finally upgraded to Fedora 34 which has GNOME Shell v40 and I upgraded the extension too.
You can check the latest release from Git https://github.com/sustmi/gnome-shell-extension-historymanager-prefix-search/releases/tag/v14 or wait until the GNOME Shell Extensions team reviews the extension on https://extensions.gnome.org/extension/544/historymanager-prefix-search/ .

**Comment by sustmi** [comment]
Also, sorry it took so long, but I do this in my free time and I do not have much motivation to update the extension unless it breaks on my system.

If you want to support the maintenace and motivate me to update for new versions of GNOME Shell earlier, you can do so: https://www.buymeacoffee.com/sustmi . :coffee: :slightly_smiling_face: 

Anyway, thank you for reporting the issue. :+1:
